### ISSUE TITLE
Incorrect Result from chars.toString() in aTaintCase0096 Method

### ISSUE THREAD

**Issue by m0unta1ner** [alipay/ant-application-security-testing-benchmark#30]
In the aTaintCase0096 method of the IAST project, using chars.toString() returns [C@59b2182 instead of the expected result. It is recommended to modify it to String.valueOf(chars).
---
It is suggested to modify chars.toString() to String.valueOf(chars) in order to obtain the actual content of the character array as a string.
``` java
// Before modification
String str = chars.toString();

// After modification
String str = String.valueOf(chars);
```

**Comment by curryooo** [comment]
good，we will fix this in next commit
