### ISSUE TITLE
testfiles folder requirement

### ISSUE THREAD

**Issue by osxtest** [alipay/ant-application-security-testing-benchmark#36]
Hi, team.

I would like to suggest that we require a `testfiles` directory to be present in the same location as the JAR file. This is because the `pathtraver` related test cases report a `No such file or directory` error when the `testfiles` directory does not exist.

```diff
 cd  target/ 
+ mkdir testfiles
 java -jar antbenchmark-0.0.1-SNAPSHOT.jar  
```

Relate source code:
https://github.com/alipay/ant-application-security-testing-benchmark/blob/c7cef8e86e426cbaba481b327e312282221a5c9b/dast-java/src/main/java/com/alipay/antbenchmark/tools/Utils.java#L20

https://github.com/alipay/ant-application-security-testing-benchmark/blob/c7cef8e86e426cbaba481b327e312282221a5c9b/dast-java/README.md?plain=1#L73-L76

**Comment by yulailailailai** [comment]
Hello, thank you for discovering an unreasonable example in the DAST range. We have added the operation of creating the testfiles directory when starting the DAST range
