### ISSUE TITLE
IAST TaintMethodUtil class not Documented in README

### ISSUE THREAD

**Issue by jojobbong** [alipay/ant-application-security-testing-benchmark#54]
The com.iast.astbenchmark.common.utils.TaintMethodUtil class appears to be a custom component within the project. However, it is not adequately documented in the README file. Consequently, users may have difficulty discovering its functionalities, particularly regarding the check and sanitizer methods within this class.

Steps to Reproduce:
1.Navigate to the README file.
2.Attempt to find documentation or references to the TaintMethodUtil class.
3.Observe the lack of information regarding its purpose and usage.

Expected Behavior:
1.The README should clearly document the purpose, usage, and functionalities of the TaintMethodUtil class, including its check and sanitizer methods.

**Comment by CC11001100** [comment]
We will later add comments to the class com.iast.astbenchmark.common.utils.TaintMethodUtil and optimize the README document. Thank you for your feedback!
