### ISSUE TITLE
Improve: Supplement Testcases for Java-SAST/Engine-Analysis-Capability by FEYSH-3

### ISSUE THREAD

**Issue by Feysh-Inc** [alipay/ant-application-security-testing-benchmark#89]
三阶段计划：

- 准确度
  - 对象敏感
    - 别名是否被污染
      - BaseAlias
      - FieldAlias
      - HeapContextAlias
      - HeapOverwriteAlias
      - HeapPointsToSelfAlias
      - InnerClassAlias
      - MultiFieldAccessAlias
  - 上下文敏感
    - 相同函数调用不同参数
    - HeapAllocSite
    - MultipleCallSite
- TODO

**Comment by AntJiuFo** [comment]
merged
