### ISSUE TITLE
A problem about sink points in part of test cases in sast-java

### ISSUE THREAD

**Issue by ningninger** [alipay/ant-application-security-testing-benchmark#90]
Title:

A problem with sink points in part of test cases in sast-java

Body:

Hello, 
I'm using the `sast-java` test cases for conducting taint analysis testing. I encountered issues while testing `completeness/base/chain/astTaint/Statement_CastStatement_002_T` and `completeness/base/chain/astTaint/Expression_MethodInvocation_Argument_002_T`.

I aim to enhance my taint analysis tool by filling in some `taint-specification`. However, I noticed these two test cases differ from others in terms of structure (including test code and referenced libraries). I'm unsure about the sink points in these two cases. According to the `README.md`, I suspect it might be `Runtime.getRuntime().exec`, but I couldn't find any code related to this sink point during manual taint tracking.

Could you please confirm the sink points for these two cases? If my suspicion is correct, could you provide more information on where to locate the sink points?

Thank you

**Comment by AntJiuFo** [comment]
感谢你的关注～～你提的问题很有价值，我们在Readme中缺失了两个sink点的描述，现已进行补充。即 https://github.com/alipay/ant-application-security-testing-benchmark/pull/91/files

**Comment by ningninger** [comment]
Thank you for your prompt response and the updates! I've reviewed the sink point descriptions you added to the Readme, and I really appreciate your quick action. It's been very helpful for us to understand the project better. Looking forward to seeing your future testing updates. Thanks again!
