### ISSUE TITLE
关于sast中测试例Expression_CallExpression_Array_001_T的错误

### ISSUE THREAD

**Issue by freeideo** [alipay/ant-application-security-testing-benchmark#95]
测试例中sink处是数组的toArray()方法，即数组的hashcode，并非数组中的元素，并不会造成污染

![image](https://github.com/user-attachments/assets/1a82ba16-75aa-4dbe-9749-a67337e11538)

**Comment by AntJiuFo** [comment]
感谢您的反馈，这里是有问题的，我们修改一下～
