### ISSUE TITLE
sink点无效 导致case 没有实际测试意义 会导致实际检出偏低

### ISSUE THREAD

**Issue by xuebibibibibi** [alipay/ant-application-security-testing-benchmark#96]
<img width="858" alt="image" src="https://github.com/user-attachments/assets/e5986049-d979-4ec5-99ea-0f562146367d">
这个sink点实际是个空mock函数 在测试靶场的时候不添加相应sink，该类sink的所有case都将无法检出，失去评测意义

**Comment by AntJiuFo** [comment]
这个sink点是为了测试一些类型而创造的一种自定义sink。因为不是所有类型都可以直接用到现有的sink点，比如Runtime.getRuntime.exec只支持String类型参数，如果用String.valueof这种二三方库函数转化，有会涉及到库函数建模的问题，有的引擎会因为没有做这个二三方库函数的建模而断链（比如codeql），因此才针对一些对象类型的case设计了一个sink点。如这个例子中的Map类型的case

**Comment by AntJiuFo** [comment]
这个sink点是为了测试一些类型而创造的一种自定义sink。因为不是所有类型都可以直接用到现有的sink点，比如Runtime.getRuntime.exec只支持String类型参数，如果用String.valueof这种二三方库函数转化，有会涉及到库函数建模的问题，有的引擎会因为没有做这个二三方库函数的建模而断链（比如codeql），因此才针对一些对象类型的case设计了一个sink点。如这个例子中的Map类型的case

**Comment by AntJiuFo** [comment]
这个sink点是为了测试一些类型而创造的一种自定义sink。因为不是所有类型都可以直接用到现有的sink点，比如Runtime.getRuntime.exec只支持String类型参数，如果用String.valueof这种二三方库函数转化，有会涉及到库函数建模的问题，有的引擎会因为没有做这个二三方库函数的建模而断链（比如codeql），因此才针对一些对象类型的case设计了一个sink点。如这个例子中的Map类型的case。

不过SinkUtil的引入确实会提高不熟悉待评测引擎自定义sink点操作的用户测试门槛，如果不能自定义sink可能这种场景就测不了了。目前还没有想好一个折中的办法，因为像interger、Map这种类型支持的原子化场景并不能找到一个合适的sink点来测试。

**Comment by AntJiuFo** [comment]
像不同的类型转化成string类型的这个过程一般都是二三方库函数来做，这个就又和适配有关系了。
我想到一个办法，针对这种原子化类型的，可以做两个case，一个是现在这种mock sink点，一种是用String.valueof这种函数做适配，两个中可以检出一个就认为达成了这个评价项（即支持这种类型的对象的污点），这样可以解决这个问题。
